/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VarejoRouteImport } from './routes/varejo'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as IndustriaRouteImport } from './routes/industria'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as IndexRouteImport } from './routes/index'

const VarejoRoute = VarejoRouteImport.update({
  id: '/varejo',
  path: '/varejo',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriaRoute = IndustriaRouteImport.update({
  id: '/industria',
  path: '/industria',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/forecast': typeof ForecastRoute
  '/fornecedores': typeof FornecedoresRoute
  '/industria': typeof IndustriaRoute
  '/integracoes': typeof IntegracoesRoute
  '/logistica': typeof LogisticaRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/varejo': typeof VarejoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/forecast': typeof ForecastRoute
  '/fornecedores': typeof FornecedoresRoute
  '/industria': typeof IndustriaRoute
  '/integracoes': typeof IntegracoesRoute
  '/logistica': typeof LogisticaRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/varejo': typeof VarejoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/forecast': typeof ForecastRoute
  '/fornecedores': typeof FornecedoresRoute
  '/industria': typeof IndustriaRoute
  '/integracoes': typeof IntegracoesRoute
  '/logistica': typeof LogisticaRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/varejo': typeof VarejoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agente'
    | '/forecast'
    | '/fornecedores'
    | '/industria'
    | '/integracoes'
    | '/logistica'
    | '/signin'
    | '/signup'
    | '/suporte'
    | '/varejo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agente'
    | '/forecast'
    | '/fornecedores'
    | '/industria'
    | '/integracoes'
    | '/logistica'
    | '/signin'
    | '/signup'
    | '/suporte'
    | '/varejo'
  id:
    | '__root__'
    | '/'
    | '/agente'
    | '/forecast'
    | '/fornecedores'
    | '/industria'
    | '/integracoes'
    | '/logistica'
    | '/signin'
    | '/signup'
    | '/suporte'
    | '/varejo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteRoute: typeof AgenteRoute
  ForecastRoute: typeof ForecastRoute
  FornecedoresRoute: typeof FornecedoresRoute
  IndustriaRoute: typeof IndustriaRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LogisticaRoute: typeof LogisticaRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SuporteRoute: typeof SuporteRoute
  VarejoRoute: typeof VarejoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/varejo': {
      id: '/varejo'
      path: '/varejo'
      fullPath: '/varejo'
      preLoaderRoute: typeof VarejoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industria': {
      id: '/industria'
      path: '/industria'
      fullPath: '/industria'
      preLoaderRoute: typeof IndustriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteRoute: AgenteRoute,
  ForecastRoute: ForecastRoute,
  FornecedoresRoute: FornecedoresRoute,
  IndustriaRoute: IndustriaRoute,
  IntegracoesRoute: IntegracoesRoute,
  LogisticaRoute: LogisticaRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SuporteRoute: SuporteRoute,
  VarejoRoute: VarejoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
